[package]
name = "pushshift-importer"
version = "0.1.0"
authors = ["Paul Ellenbogen <PaulEllenbogen@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
clap = "2.33"
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
hashbrown = "0.9"
bzip2 = "0.4"
xz2 = "0.1"
zstd = "0.6.0+zstd.1.4.8"
anyhow = "1.0"
num_cpus = "1.0"
postgres = "0.19.0"

[dependencies.rusqlite]
version = "0.24"
features = ["bundled"]